name = "tumiki-recorder"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# 静的アセット設定（Wrangler v3対応）
[assets]
directory = "./public"
binding = "ASSETS"

[observability]
enabled = true

[vars]
DATABASE_TYPE = "firestore"

# シークレット (wrangler secret putコマンドで設定)
# wrangler secret put FIREBASE_CLIENT_EMAIL
# wrangler secret put FIREBASE_PRIVATE_KEY
# wrangler secret put FIREBASE_PROJECT_ID
# wrangler secret put JWT_SECRET
