name = "kintai-runesansu03"
main = "worker.js"
compatibility_date = "2024-01-01"

# KVネームスペース設定（勤怠データ保存用）
# 以下のコマンドでKVネームスペースを作成してください：
# wrangler kv namespace create "ATTENDANCE_KV"
# 作成後、出力されたIDをここに貼り付けてください

# [[kv_namespaces]]
# binding = "ATTENDANCE_KV"
# id = "YOUR_KV_NAMESPACE_ID"
